root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/chatd ./cmd/chatd"
  bin = "tmp/chatd"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  delay = 200

[log]
  time = true